# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LatencyCheck CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore Tools
      shell: bash
      run: |
        dotnet tool restore
    - name: Run the Cake script
      uses: cake-build/cake-action@v1
      with:
        target: Publish
        cake-bootstrap: true
    - uses: actions/upload-artifact@v1
      name: Upload Artifacts
      with:
        name: lcs-archive
        path: dist/archive/
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        body: |
          Download and unpack the archive to your system from below.
        files: |
          ./dist/archive/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}